version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: analytics-node
    versions:
    - 3.5.0
    - 4.0.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: eslint-plugin-mocha
    versions:
    - 8.0.0
